# Generated by Django 3.2.4 on 2021-06-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_kitchen_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='image',
            field=models.ImageField(default='img/no_image.png', upload_to='img/'),
        ),
    ]
